### ISSUE TITLE
Make melon available in conan center

### ISSUE THREAD

**Issue by pgrossomoreira** [fhamonic/melon#5]
Hi. Will you submit a conan recipe to conan-center-index? That way I could simply add it to my conanfile. Lemon doesn't compile with recent C++ standards and it seems there aren't viable alternatives with a similar API. Otherwise, please let me know if there are well tested alternatives to Melon/Lemon/Boost that have a nice API and are available in conan.
Thank you.

**Comment by fhamonic** [comment]
Hi. Thank you for showing interest. My aim is precisely to make the library accessible through the conan-center at some point, which is why you can already build the conan package locally. But, although I'm happy with the current design, I feel that it misses a few features to make it a real package right now. For example, at the moment, we can only model directed graphs, which is fine for most algorithms since undirected graphs can be represented by directed ones by replacing each edge with a pair of reciprocating arcs, but we needs a convenient way to do it.
However, it always has to start somewhere so I may clean the code, make a github release and try to push the package on the conan-center in next weeks :)
But, since the library is still in work in progress some API changes can be required in the future and I can't recommend it for production work right now. I have not tested it but [ade](https://conan.io/center/recipes/ade?version=0.1.2d) seems to be a well-tested graph library that is part of opencv and is available in the conan-center.
